spring:
  profiles: default
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
      
zuul:
  prefix: /api
  routes:
    first-service:
      path: /first-service/**
      url: http://localhost:8100